services:
    lmdi.hidebbcode.listener:
        class: lmdi\hidebbcode\event\listener
        arguments:
            - '@user'
            - '@auth'
            - '@dbal.conn'
        tags:
            - { name: event.listener }
